server:
  port: 9001

spring:
  application:
    name: shop-user-service

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

  redis:
    host: 47.97.83.36
    password: 123456
    port: 8000

  #邮箱服务配置
  mail:
    host: smtp.126.com #发送邮件服务器
    username: wangxiaohan_tech@126.com #发送邮件的邮箱地址
    password: YVEMSPNNPGROYRSR #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: wangxiaohan_tech@126.com # 发送邮件的地址，和上面username一致

    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO